### PR TITLE
Migrate from dep to Go modules

### PR DESCRIPTION
**Pull request by sslavic**
Towards https://github.com/giantswarm/giantswarm/issues/6302

As part of updating k8s dependencies I'm taking the opportunity to try to switch to Go modules as well in the same go, starting from our leaf libraries like microerror. Our tooling like architect and e2e-harness have already been updated to Go 1.13 so Go modules support should be best ever.

Related:
https://github.com/giantswarm/giantswarm/issues/5680

### CODE REVIEW

**Comment by rossf7** [comment]
No blocker but good to hear from Mr @kopiczko and SIG Operator.

Sadly I'm not deep enough into Go modules to know if we're ready for this change.

**Comment by kopiczko** [comment]
It should be fine but I'd like to wait for this https://github.com/giantswarm/microerror/pull/22.

I'm changing the approach here to use `errors` package. This means we wouldn't have any external dependency for this project (except from `cmp` but this is only for testing so won't be pulled anyway).

Then because of backwards incompatible changes I'd like to push `v1.0.0` tag and I think `v1.0.0` should still use dep.

I'd like to discuss all of that with SIG operator first of course.

**Comment by sslavic** [comment]
@kopiczko IIUC projects which depend on microerror can continue to use dep, changing the tool used for dependency management in microerror shouldn't impact them, we can still have commits with Go modules support tagged as v1.x; IMO switch to Go modules can actually help you/us with introducing backward incompatible change like https://github.com/giantswarm/microerror/pull/22, have that signaled with changed (/v2) module path.

**Comment by kopiczko** [comment]
> IMO switch to Go modules can actually help you/us with introducing backward incompatible change

AIUI only assuming that the depending project already uses go modules.

**Comment by kopiczko** [comment]
I see something was pushed today. What is the plan here?

**Comment by sslavic** [comment]
Just rebase was pushed.

**Comment by corest** [comment]
@sslavic what is the status of this?

**Comment by sslavic** [comment]
@corest it's blocked on changes @kopiczko would like to get in first via https://github.com/giantswarm/microerror/pull/22

Once that prerequisite is done, then work can be continued as part of https://github.com/giantswarm/roadmap/issues/30 epic.

**Comment by rossf7** [comment]
I like the changes in #22 but I have a worry how big the breaking changes will be.

Should this be part of the Go modules WG so we have enough people to work on it?

cc @omegas27

**Comment by kopiczko** [comment]
@rossf7 we are working on `devctl replace` command which will make the migration process easier in scope of SIG operator SWH. We're close to wrap up this work. So I think it should be fine to do this as part of modules migration since it will be bunch of commands to be run. I don't want to have a final word here however so I leave it for the WG to decide.

**Comment by rossf7** [comment]
@kopiczko OK cool. I didn't realise we wanted to use `devctl replace` for that.

I'd like us to discuss when we kick off the WG but I'm fine with this approach.

**Comment by sslavic** [comment]
@kopiczko AFAIK there's no need for k8s lib replacements, with k8s 1.16.4+ releases Go modules compatible tags are being published. See gsctl which I updated to use k8s 1.16.4 (0.16.4 tag)

**Comment by rossf7** [comment]
@sslavic I think we will need to upgrade to K8s 1.17.1 for the Helm 3 upgrades. This is in master but we need to wait for the Helm 3.1 release.

Since moving from dep to Go modules is a big change I think it makes sense to include the K8s 1.17 upgrades. But I think this should be another topic for the WG kick off.

**Comment by sslavic** [comment]
In opsctl we have replacements but that's only because of old Helm 2 dependency (transitive to k8s.io/kubernetes) which will go away with update to Helm 3 - that's one reason for bundling switch to Go modules and Helm 3 upgrade.

Yes, I know the plan is to use k8s 1.17+, but wanted to share that Go modules compatible tags are available even in 1.16.4

**Comment by kopiczko** [comment]
I'll replace that one. I don't want to deal with conflicts.

**Pull request closed without merging**
